### ISSUE TITLE
Unable to find the paper link

### ISSUE THREAD

**Issue by abunickabhi** [ringochuchudull/CNN-Based-Hyperspectral-image-classification#1]
I am unable to find the paper which has this code implementation.

Optimizing CNN for FPGA hardware

**Comment by ringochuchudull** [comment]
https://link.springer.com/chapter/10.1007/978-3-030-17227-5_2

Hi I hope you're still interested in the paper ^^ The paper can be found from the above link and its part of LNCS.

**Comment by abunickabhi** [comment]
Thanks for sharing!
